custom:
  mail:
    from: no-reply@example.com
    message-template: |
      Hello, %s! 
      To complete your registration, please follow this link: 
      http://localhost:8080/api/auth/activation?key=%s"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testitgirls@gmail.com
    password: kmcrtlqsmlqausqr
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  # сюда же добавить конфигурацию БД